apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-server-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  hostPath:
    path: "/k8s-data/db-server"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-read-pvc
spec:
  volumeName: db-server-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-write-pvc
spec:
  volumeName: db-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
