apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-reader
spec:
  serviceName: "db-reader-service"
  replicas: 2
  selector:
    matchLabels:
      app: db-reader
  template:
    metadata:
      labels:
        app: db-reader
    spec:
      containers:
        - name: mysql
          image: 10.111.1.101:55055/mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mysql-read-host
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-writer
spec:
  serviceName: "db-writer-service"
  replicas: 1
  selector:
    matchLabels:
      app: db-writer
  template:
    metadata:
      labels:
        app: db-writer
    spec:
      containers:
        - name: mysql
          image: 10.111.1.101:55055/mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mysql-write-host
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
