apiVersion: v1
kind: Service
metadata:
  name: db-reader-svc
  labels:
    name: db-reader-svc
spec:
  selector:
    app: db-reader
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db-writer-svc
  labels:
    name: db-writer-svc
spec:
  selector:
    app: db-writer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
