apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-server-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs_share
    server: 10.111.1.101
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-server-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
