apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-server-pv
spec:
  storageClassName: db-server-sc
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  hostPath:
    path: "/k8s-data/db-server"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-server-pvc
spec:
  storageClassName: db-server-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
