apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-logs
              mountPath: /var/log/nginx
      #       - name: nginx-index
      #         mountPath: /usr/share/nginx/html
      # volumes:
      #   - name: nginx-index
      #     configMap:
      #       name: nginx-index
  volumeClaimTemplates:
    - metadata:
        name: nginx-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 500Mi
