apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              if [ "$(hostname)" = "nginx-0" ]; then
                ln -s /var/log/nginx-0 /var/log/nginx
              else
                ln -s /var/log/nginx-1 /var/log/nginx
              fi
          volumeMounts:
            - name: nginx-logs-0
              mountPath: /var/log/nginx-0
            - name: nginx-logs-1
              mountPath: /var/log/nginx-1
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-logs-0
              mountPath: /var/log/nginx-0
            - name: nginx-logs-1
              mountPath: /var/log/nginx-1
            - name: nginx-index
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-index
          configMap:
            name: nginx-index
        - name: nginx-logs-0
          persistentVolumeClaim:
            claimName: pvc-1
        - name: nginx-logs-1
          persistentVolumeClaim:
            claimName: pvc-2
