apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-0
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: nginx-index
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx
  volumes:
    - name: nginx-index
      configMap:
        name: nginx-0-index
    - name: nginx-logs
      persistentVolumeClaim:
        claimName: pvc-1
    - name: nginx-conf
      configMap:
        name: nginx-config
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: nginx-index
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx
  volumes:
    - name: nginx-index
      configMap:
        name: nginx-1-index
    - name: nginx-logs
      persistentVolumeClaim:
        claimName: pvc-2
    - name: nginx-conf
      configMap:
        name: nginx-config
