apiVersion: v1
kind: Pod
metadata:
  name: nginx-0
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable
      command:
        [
          "sh",
          "-c",
          'echo "Welcome to Nginx 0" > /usr/share/nginx/html/index.html',
        ]
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
  volumes:
    - name: nginx-logs
      persistentVolumeClaim:
        claimName: pvc-1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable
      command:
        [
          "sh",
          "-c",
          'echo "Welcome to NGINX 1" > /usr/share/nginx/html/index.html',
        ]
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
  volumes:
    - name: nginx-logs
      persistentVolumeClaim:
        claimName: pvc-2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
